### ISSUE TITLE
Set up boilerplate for the new implementation in a new branch: 'next'

### ISSUE THREAD

**Issue by cn894** [Microsoft/ApplicationInsights-JS-Mezzurite#24]
In order to create the base upon which the 2.x implementation will be built, we need a basic set of boilerplate configs and repository setup that has worked for us previously and continues to do so today. We will do so in a new branch to not disturb the default branch's appearance until we are ready to switch over.

The boilerplate will include things like .gitignore, Jest configuration for unit testing, linting via ESLint, etc.

**Comment by kawwong** [comment]
Closing, as was done in #28.
